name = "jintp"
description = "Template parser in Ada based on Jinja2"
version = "0.2.0-dev"

authors = ["Rene Hartmann"]
maintainers = ["Rene Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-2-Clause"
website = "https://github.com/rehartmann/JinTP"
tags = ["templates", "jinja", "jinja2"]
